linux:
  stage: build
  tags:
    - linux
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - .cd/bundle.sh
    - .cd/prepare_gpg.sh
    - rpm --define "_gpg_name Gled Photonenkollektiv <gled@photonenkollektiv.de>" --addsign *.rpm
    - echo "ARTIFACT_URL_RPM=${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/file/gled-${CI_COMMIT_TAG}.x86_64.rpm" >> variables.env
    - echo "ARTIFACT_URL_EXE=${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/file/gled_${CI_COMMIT_TAG}_x64-setup.exe" >> variables.env
  artifacts:
    paths:
      - "gled-${CI_COMMIT_TAG}.x86_64.rpm"
      - "gled_${CI_COMMIT_TAG}_x64-setup.exe"
    reports:
      dotenv: variables.env
    expire_in: never

darwin:
  stage: build
  tags:
    - darwin
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - .cd/bundle.sh
    - echo "ARTIFACT_URL_DMG=${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/file/gled_${CI_COMMIT_TAG}_aarch64.dmg" >> variables.env
  artifacts:
    paths:
      - "gled_${CI_COMMIT_TAG}_aarch64.dmg"
    reports:
      dotenv: variables.env
    expire_in: never

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: linux
      artifacts: true
    - job: darwin
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - echo "Creating release"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'Linux RPM (x86_64)'
          url: ${ARTIFACT_URL_RPM}
          filepath: '/assets/gled-${CI_COMMIT_TAG}.x86_64.rpm'
          link_type: package
        - name: 'Windows Installer (x86_64)'
          url: ${ARTIFACT_URL_EXE}
          filepath: '/assets/gled_${CI_COMMIT_TAG}_x64-setup.exe'
          link_type: package
        - name: 'Mac DMG (Apple Silicon)'
          url: ${ARTIFACT_URL_DMG}
          filepath: '/assets/gled_${CI_COMMIT_TAG}_aarch64.dmg'
          link_type: package

pages:
  stage: deploy
  image: fedora:latest
  needs:
    - job: linux
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  variables:
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fastest"
  script:
    - dnf -q -y install --allowerasing createrepo_c curl git dpkg-devel gnupg2 expect openssl reprepro findutils rpm-sign
    - mkdir -p public
    - .cd/create_rpm_repo.sh
    - mv rpm public/
  artifacts:
    expire_in: 1 day
    paths:
      - public
